# Generated by Django 4.1.7 on 2023-11-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_color_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, default='profile_icons/avatar_def.png', null=True, upload_to='profile_icons'),
        ),
    ]
