# Generated by Django 4.1.7 on 2023-11-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(default='Hola, esta es mi descripcion'),
        ),
    ]
