# Generated by Django 4.1.7 on 2023-10-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_miexamen_asnwers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miexamen',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
