# Generated by Django 4.1.7 on 2023-10-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_miexamen_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miexamen',
            name='time',
            field=models.CharField(max_length=1000000),
        ),
    ]
