# Generated by Django 4.1.7 on 2023-10-30 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='miperfil',
            name='invitation_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.invitation'),
        ),
    ]
