# Generated by Django 4.1.7 on 2023-10-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_miperfil_invitation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
