# Generated by Django 4.1.7 on 2023-10-08 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100000)),
                ('imgage', models.ImageField(upload_to='pregunta_images/')),
                ('weight', models.IntegerField(default=1)),
                ('answer', models.TextField(blank=True, max_length=100000, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenes.categoria')),
            ],
            options={
                'verbose_name_plural': 'preguntas',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10000)),
                ('correct', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('ask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenes.pregunta')),
            ],
            options={
                'verbose_name_plural': 'respuestas',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('time', models.FloatField(default=15.0)),
                ('date', models.DateField(auto_now_add=True)),
                ('asks', models.ManyToManyField(to='examenes.pregunta')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenes.categoria')),
            ],
            options={
                'verbose_name_plural': 'examenes',
                'ordering': ['title'],
            },
        ),
    ]
